<?php

/**
 * Push Notification Extension for Magento 2
 *
 * @author     Volodymyr Konstanchuk http://konstanchuk.com
 * @copyright  Copyright (c) 2017 The authors
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 */


/** @var $block \Konstanchuk\PushNotification\Block\Block */

$helper = $block->getHelper();
printf('<link rel="manifest" href="/%s" />', ltrim($helper->getManifestFile(), '/'));